# Generated by Django 4.1 on 2022-08-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="role",
            field=models.CharField(
                choices=[("OPERATOR", "OPERATOR"), ("ADMIN", "ADMIN")],
                default="OPERATOR",
                max_length=8,
            ),
        ),
    ]
