# Generated by Django 4.1 on 2022-08-21 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_operator_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="phone",
            field=models.PositiveIntegerField(
                default=None,
                validators=[
                    django.core.validators.MaxLengthValidator(10),
                    django.core.validators.MinLengthValidator(10),
                ],
            ),
            preserve_default=False,
        ),
    ]
