# Generated by Django 4.1 on 2022-08-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_operator_phone_operator_email_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operator",
            name="email_id",
        ),
        migrations.AddField(
            model_name="operator",
            name="firebase_uid",
            field=models.CharField(default=None, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
