# Generated by Django 4.1 on 2022-08-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_operator_email_id_operator_firebase_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(max_length=10),
        ),
    ]
