# Generated by Django 4.1 on 2022-08-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_order_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount_collected",
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("SUCCESS", "SUCCESS"),
                    ("FAIELD", "FAILED"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
