# Generated by Django 4.1 on 2022-08-25 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_order_amount_collected_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("SUCCESS", "SUCCESS"),
                    ("FAILED", "FAILED"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ShiftCashCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("cash", models.BigIntegerField()),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.operator"
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "operator")},
            },
        ),
    ]
