# Generated by Django 4.1 on 2022-08-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="order_uuid",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
