# Generated by Django 4.1 on 2022-08-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_feedback_order_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aadhaar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("aadhaar_number", models.PositiveBigIntegerField()),
                ("name", models.CharField(max_length=128)),
                ("phone_number", models.CharField(max_length=10)),
            ],
            options={
                "unique_together": {("aadhaar_number", "phone_number")},
            },
        ),
    ]
