# Generated by Django 4.1 on 2022-08-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_aadhaar_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="AadhaarLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("aadhaar_number", models.PositiveBigIntegerField()),
                ("name", models.CharField(max_length=128)),
                ("phone_number", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=250)),
                ("requested_changes", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="aadhaar",
            name="requested_changes",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
